# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'Example' do

    pod 'AFNetworking'

    pod 'SolarKit-OC', :path => '../'

    pod 'ReactiveCocoa',          '~> 2.0'

end
