source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

def pods
    pod 'AFNetworking'

#    pod 'SolarKit-OC', :path => '../'
    pod 'YYModel'
    pod 'ReactiveCocoa',          '~> 2.0'
end

target 'Example' do
    pods
end
